version: '3'

services:
  account_web:
    build: .
    ports:
      - "8080:8080"
    command: >
      sh -c "mvn -Duser.home=/var/maven clean spring-boot:run"
    volumes:
      - C:\Users\INV-0200\.m2:/var/maven/.m2
      - .:/app
    environment:
      MAVEN_CONFIG: /var/maven/.m2
    networks:
      - account_network
    depends_on:
      - account-couchdb
      - account-activemq

  account-couchdb:
    image: couchdb:3.2.2
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: root
      COUCHDB_PASSWORD: 1234
    volumes:
      - C:\Users\INV-0200\Documents\shared_docker\account_db:/opt/couchdb/data
    networks:
      - account_network

  account-activemq:
    image: symptoma/activemq:5.16.0
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - C:\Users\INV-0200\Documents\shared_docker\activemq_conf\conf:/opt/activemq/conf
    networks:
      - account_network


networks:
  account_network:
    driver: bridge