app:
  createDummyAccounts: false

spring:
  couchbase:
    username: Administrator
    password: 123456
    connection-string: "couchbase://account_couchdb"
    bucket: "accounts_bucket"

  activemq:
    broker-url: tcp://account_activemq
    user: root
    password: 1234

  graphql:
    graphiql:
      enabled: true
      path: /graphiql


#http://localhost:8091