app:
  createDummyAccounts: true

spring:
  couchbase:
    username: Administrator
    password: 123456
    connection-string: "couchbase://account_couchdb"
    bucket: "accounts_bucket"

  graphql:
    graphiql:
      enabled: true
      path: /graphiql


#http://localhost:8091