app:
  createDummyAccounts: false

spring:
  activemq:
    broker-url: tcp://account-activemq:61616
    user: admin
    password: admin

  jms:
    template:
      default-destination: account_queue

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

couchdb:
  client:
    url: http://account-couchdb:5984/
    username: root
    password: 1234
    initialization-strategy: single
    schema-operation: create

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      base-path: /
      exposure:
        include: metrics
