app:
  createDummyAccounts: false

server:
  port: 9080
  servlet:
    context-path: /account

spring:
  application:
    name: account-spring-graphql

  activemq:
    broker-url: tcp://account-activemq:61616
    user: admin
    password: admin

  jms:
    template:
      default-destination: LoyaltyLevelChange

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

couchdb:
  client:
    url: http://account-couchdb:5984/
    username: root
    password: 1234
    initialization-strategy: single
    schema-operation: create

#logging:
#  level:
#    io.opentracing: DEBUG
#    com.groocraft: DEBUG
#    org.springframework.graphql: DEBUG

opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    probabilistic-sampler:
      sampling-rate: 1.0
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces
      log-spans: true

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    health:
      base-path: "/health"
      path-mapping: ""
    web:
      base-path: /
      exposure:
        include: metrics,health
