app:
  createDummyAccounts: false

spring:
  couchbase:
    username: Administrator
    password: 123456
    connection-string: couchbase://account-couchdb
    bucket: accounts_bucket

  activemq:
    broker-url: tcp://account-activemq:61616
    user: admin
    password: admin

  jms:
    template:
      default-destination: account_queue

  graphql:
    graphiql:
      enabled: true
      path: /graphiql

management:
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      base-path: /
      exposure:
        include: metrics
